import { genId } from "./uuidHelper.js";

const ARCHIMATE_TYPE_MAP = {
  "Business Capability": "Capability",
  "Business Process": "BusinessProcess",
  "Business Function": "BusinessFunction",
  "Business Service": "BusinessService",
  "Business Actor": "BusinessActor",
  "Business Role": "BusinessRole",
  "Business Collaboration": "BusinessCollaboration",
  "Business Interface": "BusinessInterface",
  "Business Interaction": "BusinessInteraction",
  "Business Event": "BusinessEvent",
  "Business Object": "BusinessObject",
  "Contract": "Contract",
  "Product": "Product",
  "Representation": "Representation",
  "Application Component": "ApplicationComponent",
  "Application Service": "ApplicationService",
  "Application Function": "ApplicationFunction",
  "Application Interface": "ApplicationInterface",
  "Application Interaction": "ApplicationInteraction",
  "Application Process": "ApplicationProcess",
  "Application Event": "ApplicationEvent",
  "Data Entity": "DataObject",
  "Data Object": "DataObject",
  "Technology Component": "TechnologyService",
  "System Software": "SystemSoftware",
  "Technology Interface": "TechnologyInterface",
  "Network": "CommunicationNetwork",
  "Device": "Device",
  "Gap": "Gap",
  "Work Package": "WorkPackage",
  "Plateau": "Plateau",
  "Deliverable": "Deliverable",
  "Driver": "Driver",
  "Goal": "Goal",
  "Outcome": "Outcome",
  "Principle": "Principle",
  "Requirement": "Requirement",
  "Constraint": "Constraint",
  "Assumption": "Assumption",
  "Stakeholder": "Stakeholder",
  "Value Stream": "ValueStream",
  "Capability": "Capability",
  "Resource": "Resource",
  "Course Of Action": "CourseOfAction",
  "Architecture Vision": "Goal",
  "Architecture Principle": "Principle",
  "Architecture Requirement": "Requirement",
  "Architecture Contract": "Contract",
  "Architecture Decision": "Constraint",
  "Change Request": "WorkPackage",
  "Repository Object": "BusinessObject",
  "Architecture Landscape": "BusinessObject",
  "Reference Library": "BusinessObject",
  "Standards Information Base": "BusinessObject",
  "Data Store": "DataObject",
  "Data Flow": "DataObject",
  "Data Standard": "Principle",
  "Technology Standard": "Principle",
  "Platform": "TechnologyService",
  "System": "ApplicationComponent",
  "Location": "BusinessActor",
  "Communication Network": "CommunicationNetwork"
};

function xmlEscape(str) {
  return (str || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateArchiMateXML(artefactName, objects) {
  const modelId = `id-${genId()}`;

  const elemDefs = objects.map((obj, i) => ({
    id: `id-elem-${i}-${genId()}`,
    obj
  }));

  const nameToId = {};
  elemDefs.forEach(({ id, obj }) => { nameToId[obj.name] = id; });

  const elemXml = elemDefs.map(({ id, obj }) => {
    const type = ARCHIMATE_TYPE_MAP[obj.objectType] || "BusinessObject";
    return `    <element identifier="${id}" xsi:type="archimate3:${type}">
      <name xml:lang="en">${xmlEscape(obj.name)}</name>
      <documentation xml:lang="en">${xmlEscape(obj.description)}</documentation>
    </element>`;
  }).join("\n");

  const relXml = elemDefs
    .filter(({ obj }) => obj.parent && nameToId[obj.parent])
    .map(({ id, obj }, i) => {
      const relId = `id-rel-${i}-${genId()}`;
      const sourceId = nameToId[obj.parent];
      return `    <relationship identifier="${relId}" xsi:type="archimate3:Composition" source="${sourceId}" target="${id}" />`;
    }).join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<model xmlns="http://www.opengroup.org/xsd/archimate/3.0/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.opengroup.org/xsd/archimate/3.0/ http://www.opengroup.org/xsd/archimate/3.1/archimate3_Diagram.xsd"
       identifier="${modelId}"
       version="1.1">
  <name xml:lang="en">${xmlEscape(artefactName)}</name>
  <documentation xml:lang="en">Generated by EA Co-Pilot — velocityarchitecture.com.au</documentation>
  <elements>
${elemXml}
  </elements>
  <relationships>
${relXml}
  </relationships>
</model>`;
}
